language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: oa/DKxeKBthtOhDM1pD0gFtbCh9yzC2SdvtoFNwaMsJMaGRYQHSta3ryibo1ncxKbH4m1o9hNWZCkHNkFki5u4SIaSt26a0shgJNuUqxWw1m1MQ1MJ70UR+AEZAPfHigweD+h1gFyWa/tlegI0QdQoima7B00OboSa92Yok4zUXANkrF2sPYUHbtF2bnkUj4iPqUWeVtGkYWMO6jjowqP2PLAYAwhmIJDjg1QK46YRJCRHVtck7yg6b71zVb0cVudGesnmvZOrogcXwSNnp5246CgB7JCxBKC9vKH7x6ZO4ldIrE1ZfIAQ0kASZCa3Lwy7D1GA4TF8u67gbzmooK+EqTx+HtqhlmQoel5ZMmueyBiawH+ylXBYGtsccsuFMzmOHWI9ACtWYYsoUsjuLJsZWhdFWpyn2OG5fVGJ8h3Um4g2Y0n7YizQ7vKwUCiTO8cn7BbOuYmtsWY6jY4saVx0zNSHT9m8bjUl6Voe6OzLrSqjgjGba6ha/iL7MBdV7QtTC93NJ2rOuiY47QWkJppvJ6jtDl97nUzTlf7sQGDMbLlSRRjKtHuQmI+AOM0wGly32GE01FmBa9sZ6fDd0b4el1Mp4S1YZHdXueo/WTr2xd0gDHxed5FoT1rHCSp3e+fXpN8ONKb6swwxuWSEnappYFOWJ/QecpgBaCTRhpqXo=
  app: react-hot-cold
  on:
    repo: Mrjustinfry/react-hot-cold
